name: SnowSQL Key Pair Authentication - Github Secrets

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "The name of the target environment as defined in the github repo settings"
        required: true
        default: 'Dev'

jobs:
  hello-world:
    name: Hello, World!
    runs-on: ubuntu-latest
    environment:
      name: '${{ github.event.inputs.environment }}'
      
    steps:
      - name: Fail if required secret 'SNOWFLAKE_PRIVATE_KEY_B64' is not set on the environment
        env:
          snowflake_private_key_b64: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}
        if: '!env.snowflake_private_key_b64'
        run: echo "::error ::The secret 'SNOWFLAKE_PRIVATE_KEY_B64' is not set for the environment '${{ github.event.inputs.environment }}'." && exit 1
        
      - name: Fail if required secret 'SNOWFLAKE_PRIVATE_KEY_PASSPHRASE' is not set on the environment
        env:
          snowflake_private_key_passphrase: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        if: '!env.snowflake_private_key_passphrase'
        run: echo "::error ::The secret 'SNOWFLAKE_PRIVATE_KEY_PASSPHRASE' is not set for the environment '${{ github.event.inputs.environment }}'." && exit 1

      - name: Fail if required secret 'SNOWFLAKE_USERNAME' is not set on the environment
        env:
          snowflake_username: ${{ secrets.SNOWFLAKE_USERNAME }}
        if: '!env.snowflake_username'
        run: echo "::error ::The secret 'SNOWFLAKE_USERNAME' is not set for the environment '${{ github.event.inputs.environment }}'." && exit 1
        
      - name: Fail if required secret 'SNOWFLAKE_ACCOUNT' is not set on the environment
        env:
          snowflake_account: ${{ secrets.SNOWFLAKE_ACCOUNT }}
        if: '!env.snowflake_account'
        run: echo "::error ::The secret 'SNOWFLAKE_ACCOUNT' is not set for the environment '${{ github.event.inputs.environment }}'." && exit 1

      - uses: actions/checkout@v3
      - run: npm install config
      
      - name: Install SnowSQL CLI
        env:
          SNOWSQL_DEST: '/home/runner/.snowsql/bin'
          SNOWSQL_LOGIN_SHELL: '/home/runner/.profile'
        run: |
          curl -O https://sfc-repo.snowflakecomputing.com/snowsql/bootstrap/1.2/linux_x86_64/snowsql-1.2.22-linux_x86_64.bash
          bash snowsql-1.2.22-linux_x86_64.bash
          
      - name: DEBUG
        run: |
          base64 --version
          ~/.snowsql/bin/snowsql --version
          
      - name: Copy private key into .p8 file in .snowsql directory
        run: 'echo $SSH_KEY | base64 -di > ~/.snowsql/rsa_key.p8'
        env:
          SSH_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_B64 }}
          
      - name: Connect to Snowflake
        env:
          SNOWSQL_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
        run: |
          ~/.snowsql/bin/snowsql -a ${{ secrets.SNOWFLAKE_ACCOUNT }} -u ${{ secrets.SNOWFLAKE_USERNAME }} --private-key-path ~/.snowsql/rsa_key.p8 -f ./hello_world.sql
